# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-15 14:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='lecture',
            field=models.ManyToManyField(blank=True, null=True, related_name='students', to='lectures.Lecture'),
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(max_length=100),
        ),
    ]
