# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-14 14:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('subject_area', models.CharField(max_length=100)),
                ('where_from', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField(verbose_name='date of birth')),
            ],
        ),
    ]
