# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-15 07:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lecture_name', models.CharField(max_length=200)),
                ('subject_area', models.CharField(max_length=200)),
                ('lecture_code', models.CharField(max_length=50)),
            ],
        ),
    ]
